name: Release
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.4
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.4
      with:
        node-version: '16.x'
    - name: Install Dependencies
      run: npm ci
    - name: Publish to NPM
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      run: |
        VERSION=$(node -p -e "require('./package.json').version")
        echo "Publishing version $VERSION to NPM..."
        npm publish
